SET NAMES utf8mb4;

CREATE TABLE korisnik (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    lozinka VARCHAR(255) NOT NULL,
    ime VARCHAR(255) NOT NULL,
    prezime VARCHAR(255) NOT NULL
);

CREATE TABLE projekat (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    naziv VARCHAR(255) NOT NULL,
    opis VARCHAR(2000) NOT NULL,
    rok_realizacije DATE NOT NULL
);

CREATE TABLE zadatak (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    projekat_id BIGINT NOT NULL,
    opis VARCHAR(2000) NOT NULL,
    status INT NOT NULL CHECK (status BETWEEN 0 AND 2),
    prioritet INT NOT NULL CHECK (prioritet BETWEEN 0 AND 2),
    FOREIGN KEY (projekat_id) REFERENCES projekat (id) ON DELETE CASCADE
);

INSERT INTO korisnik (email, lozinka, ime, prezime) VALUES
    ('aleksandar@kwa.rs', '$2y$10$skOElXwVcMOhEPKXoFs67.zItMbNOm5/lnErsooaT.9duw2fBdRLS', 'Aleksandar', 'Čolović'),
    ('marko@kwa.rs', '$2y$10$skOElXwVcMOhEPKXoFs67.zItMbNOm5/lnErsooaT.9duw2fBdRLS', 'Marko', 'Marković');

INSERT INTO projekat (naziv, opis, rok_realizacije) VALUES
    ('Veb prodavnica', 'Onlajn prodavnica sa korpom, plaćanjem i praćenjem porudžbina.', '2026-11-30'),
    ('Mobilna aplikacija za dostavu', 'Aplikacija za naručivanje hrane sa praćenjem kurira u realnom vremenu.', '2027-10-28'),
    ('Interni portal', 'Portal za zaposlene: vesti, dokumenti i evidencija odsustava.', '2027-07-25'),
    ('Migracija na oblak', 'Prebacivanje postojeće infrastrukture na Kubernetes klaster.', '2026-12-06'),
    ('Sistem za rezervaciju termina', 'Zakazivanje termina kod lekara sa podsetnicima putem SMS-a.', '2027-02-27'),
    ('Evidencija radnog vremena', 'Prijava dolaska i odlaska zaposlenih sa mesečnim izveštajima.', '2027-02-13'),
    ('Biblioteka digitalnih knjiga', 'Katalog e-knjiga sa iznajmljivanjem i čitanjem u browseru.', '2027-10-18'),
    ('Platforma za onlajn kurseve', 'Video lekcije, kvizovi i sertifikati za polaznike.', '2027-02-12'),
    ('Aplikacija za praćenje troškova', 'Lični budžet sa kategorijama, grafikonima i izvozom u CSV.', '2027-06-03'),
    ('Sistem za upravljanje skladištem', 'Prijem, izdavanje i popis robe sa bar-kod skenerom.', '2027-05-23'),
    ('Portal za studente', 'Prijava ispita, pregled ocena i raspored nastave.', '2027-02-17'),
    ('Chat aplikacija za timove', 'Kanali, direktne poruke i deljenje fajlova u realnom vremenu.', '2027-10-12'),
    ('Sistem za izdavanje faktura', 'Kreiranje, slanje i arhiviranje faktura sa PDF izvozom.', '2027-01-30'),
    ('Aplikacija za teretanu', 'Članarine, raspored treninga i praćenje napretka članova.', '2027-11-30'),
    ('Nadzor IoT senzora', 'Prikupljanje očitavanja sa senzora temperature i vlažnosti.', '2026-11-24'),
    ('Sistem za podršku korisnicima', 'Tiketi, prioriteti i baza znanja za agente podrške.', '2027-04-29'),
    ('Aplikacija za recepte', 'Pretraga recepata po sastojcima i nedeljni plan obroka.', '2027-09-28'),
    ('Platforma za oglase nekretnina', 'Objavljivanje oglasa sa mapom i filterima po ceni i lokaciji.', '2026-12-16'),
    ('Sistem za upravljanje flotom', 'Praćenje vozila, servisa i potrošnje goriva.', '2027-10-24'),
    ('Aplikacija za parking', 'Pronalaženje slobodnih mesta i plaćanje parkiranja.', '2026-11-04'),
    ('Portal za javne nabavke', 'Objave tendera, prijave ponuđača i evaluacija ponuda.', '2026-10-20'),
    ('Sistem za hotelske rezervacije', 'Dostupnost soba, cenovnici i potvrde rezervacija.', '2026-11-16'),
    ('Aplikacija za vremensku prognozu', 'Prognoza po gradovima sa upozorenjima na nepogode.', '2027-09-19'),
    ('Platforma za crowdfunding', 'Kampanje, donacije i izveštaji o prikupljenim sredstvima.', '2026-12-29'),
    ('Sistem za upravljanje projektnom dokumentacijom', 'Verzionisanje dokumenata sa odobravanjem izmena.', '2027-05-04'),
    ('Aplikacija za deljenje prevoza', 'Uparivanje vozača i putnika na istoj ruti.', '2027-01-19'),
    ('Portal za zakazivanje tehničkog pregleda', 'Termini, cenovnik i podsetnici za registraciju vozila.', '2026-11-29'),
    ('Sistem za elektronsko glasanje', 'Anonimno glasanje sa proverom identiteta i rezultatima uživo.', '2027-07-26'),
    ('Aplikacija za učenje jezika', 'Lekcije, vežbe izgovora i dnevni ciljevi.', '2026-11-26'),
    ('Platforma za muzičke događaje', 'Prodaja karata i mapa sedišta za koncerte.', '2027-01-11'),
    ('Sistem za upravljanje restoranom', 'Meni, porudžbine po stolovima i kuhinjski ekran.', '2027-02-20'),
    ('Aplikacija za kućni budžet', 'Zajednički troškovi domaćinstva sa podelom po članovima.', '2027-06-25'),
    ('Portal za volontere', 'Prijava na akcije, evidencija sati i sertifikati.', '2027-09-29'),
    ('Sistem za praćenje pošiljki', 'Statusi pošiljki, obaveštenja i istorija isporuka.', '2027-06-05'),
    ('Aplikacija za meditaciju', 'Vođene sesije, statistika i podsetnici.', '2027-10-23'),
    ('Platforma za freelance poslove', 'Oglasi, ponude i sigurno plaćanje po završetku.', '2027-02-07'),
    ('Sistem za upravljanje bioskopom', 'Repertoar, projekcije i prodaja karata.', '2027-03-23'),
    ('Aplikacija za praćenje zdravlja', 'Unos težine, pritiska i koraka sa grafikonima.', '2027-01-02'),
    ('Portal za osiguranje', 'Ponude polisa, prijava štete i praćenje zahteva.', '2027-10-23'),
    ('Sistem za obračun zarada', 'Obračun plata, doprinosa i generisanje platnih listića.', '2027-03-26'),
    ('Aplikacija za kućne ljubimce', 'Vakcinacije, pregledi i podsetnici za vlasnike.', '2027-02-15'),
    ('Platforma za podkaste', 'Objavljivanje epizoda, pretplate i statistika slušanja.', '2027-08-15'),
    ('Sistem za upravljanje voznim redom', 'Linije, polasci i obaveštenja o kašnjenjima.', '2027-03-22'),
    ('Aplikacija za kviz', 'Pitanja po kategorijama i rang lista igrača.', '2027-03-08'),
    ('Portal za gradske prijave', 'Prijava komunalnih problema sa fotografijom i lokacijom.', '2026-11-13'),
    ('Sistem za upravljanje laboratorijom', 'Uzorci, analize i izveštaji o rezultatima.', '2027-07-09'),
    ('Aplikacija za bicikliste', 'Rute, statistika vožnji i deljenje sa prijateljima.', '2026-11-06'),
    ('Platforma za vebinare', 'Prenos uživo, pitanja publike i snimci.', '2027-10-10'),
    ('Sistem za evidenciju opreme', 'Zaduženja, servisi i amortizacija opreme.', '2027-05-11'),
    ('Aplikacija za planiranje putovanja', 'Itinerer, budžet i deljenje plana sa saputnicima.', '2026-10-01');

INSERT INTO zadatak (projekat_id, opis, status, prioritet) VALUES
    (1, 'Dizajnirati šemu baze podataka za proizvode i porudžbine', 2, 2),
    (1, 'Implementirati katalog proizvoda sa pretragom', 1, 2),
    (1, 'Napraviti korpu za kupovinu', 1, 1),
    (1, 'Integrisati plaćanje karticom', 0, 2),
    (1, 'Slanje e-pošte o statusu porudžbine', 0, 0),
    (1, 'Podesiti rezervne kopije baze', 0, 0),
    (1, 'Dodati audit log administratorskih akcija', 0, 2),
    (1, 'Implementirati arhiviranje starih zapisa', 1, 1),
    (1, 'Podesiti red čekanja za obradu poruka', 0, 1),
    (1, 'Dodati paginaciju i sortiranje na listu', 2, 1),
    (1, 'Napisati dokumentaciju API-ja', 0, 1),
    (1, 'Implementirati favorite i liste želja', 1, 1),
    (1, 'Napraviti izveštaj o aktivnosti korisnika', 0, 1),
    (1, 'Implementirati offline režim rada', 0, 0),
    (1, 'Sprovesti testiranje opterećenja', 1, 1),
    (1, 'Napraviti widget za brzi pregled', 0, 2),
    (1, 'Dodati lenjo učitavanje slika', 0, 1),
    (1, 'Implementirati SSO prijavu preko Google naloga', 0, 2),
    (1, 'Dodati ocenjivanje i recenzije', 1, 2),
    (1, 'Napisati uputstvo za korisnike', 0, 2),
    (1, 'Dodati keširanje čestih upita', 2, 2),
    (1, 'Definisati korisničke priče i kriterijume prihvatanja', 0, 1),
    (1, 'Implementirati QR kodove za brzi pristup', 2, 1),
    (1, 'Implementirati uloge i dozvole', 2, 1),
    (1, 'Implementirati pretragu po ključnoj reči', 2, 1),
    (2, 'Prijava korisnika putem telefona', 2, 1),
    (2, 'Mapa sa pozicijom kurira', 1, 2),
    (2, 'Ocenjivanje restorana', 0, 0),
    (2, 'Push obaveštenja o dostavi', 0, 1),
    (2, 'Validirati unos na serverskoj strani', 2, 1),
    (2, 'Implementirati registraciju korisnika', 1, 2),
    (2, 'Podesiti nadzor dostupnosti servisa', 0, 0),
    (2, 'Nadograditi framework na najnoviju verziju', 0, 0),
    (2, 'Dodati paginaciju i sortiranje na listu', 1, 1),
    (2, 'Napraviti izveštaj o aktivnosti korisnika', 1, 1),
    (2, 'Ispraviti greške prijavljene u beta testiranju', 1, 2),
    (2, 'Integrisati sa spoljnim servisom za plaćanje', 0, 1),
    (2, 'Napraviti glavnu navigaciju i layout', 1, 2),
    (2, 'Dodati webhook obaveštenja za partnere', 2, 1),
    (2, 'Podesiti logovanje i praćenje grešaka', 2, 2),
    (2, 'Dodati filtere po kategoriji i datumu', 0, 2),
    (2, 'Dodati nedeljni pregled putem e-pošte', 0, 1),
    (2, 'Održati radionicu za krajnje korisnike', 2, 1),
    (2, 'Pregledati i zatvoriti stare tikete', 1, 2),
    (2, 'Smanjiti veličinu JavaScript bundle-a', 2, 2),
    (2, 'Dodati indekse na tabele sa najviše upita', 1, 0),
    (2, 'Implementirati offline režim rada', 0, 1),
    (2, 'Proveriti kontrast boja prema WCAG smernicama', 0, 1),
    (2, 'Napisati skriptu za početne podatke', 0, 1),
    (2, 'Dodati lenjo učitavanje slika', 0, 0),
    (3, 'Objavljivanje vesti sa uređivačem teksta', 2, 0),
    (3, 'Zahtev za godišnji odmor sa odobravanjem', 1, 1),
    (3, 'Pretraga dokumenata po nazivu i tipu', 0, 1),
    (3, 'Smanjiti veličinu JavaScript bundle-a', 0, 1),
    (3, 'Implementirati uloge i dozvole', 2, 2),
    (3, 'Implementirati QR kodove za brzi pristup', 2, 1),
    (3, 'Implementirati izvoz podataka u CSV', 0, 2),
    (3, 'Optimizovati spore SQL upite', 1, 0),
    (3, 'Dodati filtere po kategoriji i datumu', 0, 0),
    (3, 'Napraviti izveštaj o aktivnosti korisnika', 2, 0),
    (3, 'Postaviti Docker okruženje za razvoj', 0, 1),
    (3, 'Pregledati i zatvoriti stare tikete', 2, 0),
    (3, 'Dodati kompresiju i promenu veličine slika', 1, 1),
    (3, 'Napraviti stranicu sa uslovima korišćenja', 0, 1),
    (3, 'Implementirati responzivan prikaz za mobilne uređaje', 0, 2),
    (3, 'Definisati korisničke priče i kriterijume prihvatanja', 1, 2),
    (3, 'Podesiti rezervne kopije baze', 0, 1),
    (3, 'Implementirati SSO prijavu preko Google naloga', 0, 1),
    (3, 'Validirati forme na klijentskoj strani', 1, 1),
    (3, 'Ukloniti zastarele zavisnosti', 0, 1),
    (3, 'Napisati dokumentaciju API-ja', 0, 2),
    (3, 'Integrisati sa spoljnim servisom za plaćanje', 0, 1),
    (3, 'Validirati unos na serverskoj strani', 2, 1),
    (3, 'Dodati audit log administratorskih akcija', 2, 0),
    (3, 'Dodati istoriju izmena za glavne entitete', 1, 2),
    (4, 'Popis postojećih servisa i zavisnosti', 2, 2),
    (4, 'Napisati Helm chart-ove za servise', 1, 2),
    (4, 'Podesiti nadzor i alarmiranje', 0, 1),
    (4, 'Testirati oporavak nakon otkaza čvora', 0, 0),
    (4, 'Podesiti red čekanja za obradu poruka', 1, 1),
    (4, 'Napraviti stranicu statusa sistema', 1, 0),
    (4, 'Dodati uvoz podataka iz Excel fajla', 2, 2),
    (4, 'Podesiti nadzor dostupnosti servisa', 2, 2),
    (4, 'Validirati forme na klijentskoj strani', 0, 2),
    (4, 'Dodati tamnu temu', 2, 1),
    (4, 'Ukloniti zastarele zavisnosti', 0, 2),
    (4, 'Napraviti kontrolnu tablu sa statistikom', 2, 1),
    (4, 'Dodati prečice na tastaturi', 2, 1),
    (4, 'Dodati kompresiju i promenu veličine slika', 0, 1),
    (4, 'Ispraviti greške prijavljene u beta testiranju', 1, 1),
    (4, 'Optimizovati vreme učitavanja početne stranice', 0, 1),
    (4, 'Sprovesti testiranje opterećenja', 1, 1),
    (4, 'Implementirati uloge i dozvole', 0, 0),
    (4, 'Napisati skriptu za početne podatke', 0, 1),
    (4, 'Podesiti HTTPS i sertifikate', 0, 0),
    (4, 'Integrisati push obaveštenja', 2, 0),
    (4, 'Implementirati otpremanje fajlova', 1, 2),
    (4, 'Planirati drugu fazu razvoja', 1, 0),
    (4, 'Napraviti admin panel za upravljanje sadržajem', 1, 1),
    (4, 'Implementirati brisanje naloga sa potvrdom', 0, 2),
    (5, 'Podesiti rezervne kopije baze', 1, 2),
    (5, 'Dodati tamnu temu', 2, 1),
    (5, 'Implementirati otpremanje fajlova', 2, 1),
    (5, 'Dodati indekse na tabele sa najviše upita', 2, 1),
    (5, 'Dodati zaboravljenu lozinku sa slanjem e-pošte', 2, 1),
    (5, 'Nacrtati wireframe glavnih ekrana', 1, 1),
    (5, 'Napisati end-to-end testove za glavne tokove', 0, 1),
    (5, 'Refaktorisati servisni sloj', 0, 2),
    (5, 'Sprovesti testiranje opterećenja', 2, 0),
    (5, 'Implementirati zakazane zadatke u pozadini', 2, 1),
    (5, 'Implementirati prijavu sa JWT tokenom', 2, 1),
    (5, 'Napisati REST endpoint za detalje stavke', 0, 1),
    (5, 'Dodati keširanje čestih upita', 1, 0),
    (5, 'Dizajnirati šemu baze podataka', 1, 0),
    (5, 'Napisati skriptu za početne podatke', 0, 1),
    (5, 'Dodati filtere po kategoriji i datumu', 1, 1),
    (5, 'Dodati ocenjivanje i recenzije', 0, 1),
    (5, 'Podesiti HTTPS i sertifikate', 0, 1),
    (5, 'Pregledati i zatvoriti stare tikete', 0, 1),
    (5, 'Održati radionicu za krajnje korisnike', 0, 0),
    (5, 'Podesiti CI/CD pipeline', 1, 1),
    (5, 'Proveriti kontrast boja prema WCAG smernicama', 2, 1),
    (5, 'Optimizovati vreme učitavanja početne stranice', 0, 0),
    (5, 'Dodati uvoz podataka iz Excel fajla', 0, 0),
    (5, 'Implementirati meko brisanje zapisa', 0, 1),
    (6, 'Podesiti rezervne kopije baze', 2, 1),
    (6, 'Validirati forme na klijentskoj strani', 0, 1),
    (6, 'Dodati nedeljni pregled putem e-pošte', 1, 1),
    (6, 'Dodati ocenjivanje i recenzije', 1, 2),
    (6, 'Napisati REST endpoint za listu stavki', 1, 0),
    (6, 'Integrisati push obaveštenja', 1, 0),
    (6, 'Dodati lenjo učitavanje slika', 2, 2),
    (6, 'Podesiti CI/CD pipeline', 2, 2),
    (6, 'Implementirati arhiviranje starih zapisa', 1, 2),
    (6, 'Implementirati otpremanje fajlova', 1, 0),
    (6, 'Implementirati dvofaktorsku prijavu', 0, 1),
    (6, 'Podesiti nadzor dostupnosti servisa', 0, 1),
    (6, 'Pregledati i zatvoriti stare tikete', 2, 0),
    (6, 'Implementirati prijavu sa JWT tokenom', 0, 2),
    (6, 'Nacrtati wireframe glavnih ekrana', 1, 1),
    (6, 'Optimizovati spore SQL upite', 2, 1),
    (6, 'Integrisati sa spoljnim servisom za plaćanje', 2, 1),
    (6, 'Napraviti widget za brzi pregled', 1, 0),
    (6, 'Napisati dokumentaciju API-ja', 1, 0),
    (6, 'Implementirati QR kodove za brzi pristup', 1, 1),
    (6, 'Implementirati responzivan prikaz za mobilne uređaje', 0, 0),
    (6, 'Proveriti kontrast boja prema WCAG smernicama', 1, 2),
    (6, 'Dodati kolačić baner i politiku privatnosti', 0, 0),
    (6, 'Podesiti logovanje i praćenje grešaka', 1, 1),
    (6, 'Napraviti stranicu sa podešavanjima', 2, 0),
    (7, 'Dodati nedeljni pregled putem e-pošte', 1, 1),
    (7, 'Nacrtati wireframe glavnih ekrana', 0, 0),
    (7, 'Dodati deljenje stavki putem linka', 0, 0),
    (7, 'Podesiti red čekanja za obradu poruka', 2, 0),
    (7, 'Dodati webhook obaveštenja za partnere', 0, 1),
    (7, 'Ispraviti greške prijavljene u beta testiranju', 0, 1),
    (7, 'Napraviti stranicu sa uslovima korišćenja', 1, 1),
    (7, 'Optimizovati vreme učitavanja početne stranice', 0, 1),
    (7, 'Integrisati slanje e-pošte', 2, 2),
    (7, 'Podesiti nadzor dostupnosti servisa', 0, 0),
    (7, 'Napisati migracije za početnu šemu', 2, 2),
    (7, 'Integrisati push obaveštenja', 2, 0),
    (7, 'Podesiti rezervne kopije baze', 1, 0),
    (7, 'Smanjiti veličinu JavaScript bundle-a', 0, 1),
    (7, 'Napraviti glavnu navigaciju i layout', 0, 2),
    (7, 'Dodati tamnu temu', 1, 1),
    (7, 'Implementirati favorite i liste želja', 0, 0),
    (7, 'Implementirati pretragu po ključnoj reči', 1, 2),
    (7, 'Implementirati arhiviranje starih zapisa', 2, 2),
    (7, 'Definisati korisničke priče i kriterijume prihvatanja', 0, 2),
    (7, 'Implementirati višejezičnost', 1, 0),
    (7, 'Dodati zaboravljenu lozinku sa slanjem e-pošte', 0, 1),
    (7, 'Ukloniti zastarele zavisnosti', 1, 1),
    (7, 'Implementirati meko brisanje zapisa', 0, 0),
    (7, 'Dodati paginaciju i sortiranje na listu', 0, 2),
    (8, 'Napraviti glavnu navigaciju i layout', 1, 0),
    (8, 'Smanjiti veličinu JavaScript bundle-a', 0, 0),
    (8, 'Dodati nedeljni pregled putem e-pošte', 0, 1),
    (8, 'Dodati kompresiju i promenu veličine slika', 0, 1),
    (8, 'Podesiti logovanje i praćenje grešaka', 1, 2),
    (8, 'Dodati zaštitu od prekomernog broja zahteva', 2, 2),
    (8, 'Pregledati i zatvoriti stare tikete', 1, 0),
    (8, 'Implementirati offline režim rada', 2, 1),
    (8, 'Dodati filtere po kategoriji i datumu', 1, 2),
    (8, 'Refaktorisati servisni sloj', 0, 2),
    (8, 'Dodati istoriju izmena za glavne entitete', 2, 1),
    (8, 'Napraviti widget za brzi pregled', 1, 1),
    (8, 'Održati radionicu za krajnje korisnike', 1, 0),
    (8, 'Proveriti kontrast boja prema WCAG smernicama', 2, 2),
    (8, 'Dodati ocenjivanje i recenzije', 0, 2),
    (8, 'Dizajnirati šemu baze podataka', 2, 0),
    (8, 'Dodati lenjo učitavanje slika', 1, 1),
    (8, 'Implementirati zakazane zadatke u pozadini', 0, 1),
    (8, 'Napisati end-to-end testove za glavne tokove', 1, 1),
    (8, 'Implementirati dvofaktorsku prijavu', 0, 0),
    (8, 'Napisati REST endpoint za detalje stavke', 2, 0),
    (8, 'Napraviti admin panel za upravljanje sadržajem', 1, 1),
    (8, 'Implementirati izvoz izveštaja u PDF', 0, 2),
    (8, 'Ispraviti greške prijavljene u beta testiranju', 1, 1),
    (8, 'Integrisati push obaveštenja', 0, 1),
    (9, 'Dodati indekse na tabele sa najviše upita', 0, 1),
    (9, 'Implementirati SSO prijavu preko Google naloga', 1, 1),
    (9, 'Sprovesti bezbednosni pregled zavisnosti', 0, 1),
    (9, 'Pregledati i zatvoriti stare tikete', 0, 2),
    (9, 'Podesiti CI/CD pipeline', 2, 0),
    (9, 'Nadograditi framework na najnoviju verziju', 0, 2),
    (9, 'Validirati forme na klijentskoj strani', 2, 1),
    (9, 'Dizajnirati šemu baze podataka', 0, 0),
    (9, 'Dodati webhook obaveštenja za partnere', 1, 0),
    (9, 'Dodati kolačić baner i politiku privatnosti', 1, 0),
    (9, 'Refaktorisati servisni sloj', 1, 1),
    (9, 'Planirati drugu fazu razvoja', 1, 2),
    (9, 'Implementirati izvoz podataka u CSV', 0, 2),
    (9, 'Implementirati višejezičnost', 1, 1),
    (9, 'Napraviti stranicu sa podešavanjima', 2, 1),
    (9, 'Implementirati arhiviranje starih zapisa', 2, 1),
    (9, 'Proveriti kontrast boja prema WCAG smernicama', 1, 1),
    (9, 'Implementirati meko brisanje zapisa', 0, 1),
    (9, 'Dodati uvoz podataka iz Excel fajla', 2, 1),
    (9, 'Implementirati registraciju korisnika', 0, 2),
    (9, 'Napisati end-to-end testove za glavne tokove', 1, 0),
    (9, 'Dodati zaboravljenu lozinku sa slanjem e-pošte', 1, 0),
    (9, 'Smanjiti veličinu JavaScript bundle-a', 2, 2),
    (9, 'Implementirati QR kodove za brzi pristup', 0, 0),
    (9, 'Napisati skriptu za početne podatke', 1, 1),
    (10, 'Integrisati slanje e-pošte', 0, 1),
    (10, 'Napraviti kontrolnu tablu sa statistikom', 2, 1),
    (10, 'Implementirati registraciju korisnika', 2, 1),
    (10, 'Nadograditi framework na najnoviju verziju', 0, 1),
    (10, 'Implementirati responzivan prikaz za mobilne uređaje', 2, 0),
    (10, 'Napisati end-to-end testove za glavne tokove', 1, 0),
    (10, 'Napraviti izveštaj o aktivnosti korisnika', 2, 0),
    (10, 'Implementirati SSO prijavu preko Google naloga', 1, 1),
    (10, 'Smanjiti veličinu JavaScript bundle-a', 0, 1),
    (10, 'Napisati migracije za početnu šemu', 2, 1),
    (10, 'Implementirati meko brisanje zapisa', 1, 1),
    (10, 'Napisati dokumentaciju API-ja', 0, 1),
    (10, 'Implementirati arhiviranje starih zapisa', 1, 2),
    (10, 'Dodati kolačić baner i politiku privatnosti', 1, 1),
    (10, 'Implementirati QR kodove za brzi pristup', 2, 0),
    (10, 'Napisati REST endpoint za listu stavki', 0, 2),
    (10, 'Planirati drugu fazu razvoja', 0, 1),
    (10, 'Implementirati zakazane zadatke u pozadini', 1, 0),
    (10, 'Podesiti red čekanja za obradu poruka', 0, 1),
    (10, 'Sprovesti bezbednosni pregled zavisnosti', 2, 2),
    (10, 'Napraviti glavnu navigaciju i layout', 0, 1),
    (10, 'Implementirati komentare na stavkama', 0, 2),
    (10, 'Postaviti Docker okruženje za razvoj', 1, 0),
    (10, 'Integrisati sa spoljnim servisom za plaćanje', 1, 1),
    (10, 'Definisati korisničke priče i kriterijume prihvatanja', 1, 1),
    (11, 'Napraviti stranicu sa uslovima korišćenja', 1, 0),
    (11, 'Implementirati SSO prijavu preko Google naloga', 2, 1),
    (11, 'Validirati forme na klijentskoj strani', 0, 1),
    (11, 'Dodati paginaciju i sortiranje na listu', 1, 1),
    (11, 'Napraviti glavnu navigaciju i layout', 1, 0),
    (11, 'Implementirati offline režim rada', 2, 0),
    (11, 'Napisati dokumentaciju API-ja', 0, 0),
    (11, 'Pregledati i zatvoriti stare tikete', 1, 0),
    (11, 'Održati radionicu za krajnje korisnike', 2, 1),
    (11, 'Prevesti interfejs na engleski', 0, 1),
    (11, 'Dodati ocenjivanje i recenzije', 0, 2),
    (11, 'Implementirati registraciju korisnika', 2, 1),
    (11, 'Implementirati zakazane zadatke u pozadini', 0, 1),
    (11, 'Sprovesti bezbednosni pregled zavisnosti', 0, 2),
    (11, 'Dodati indekse na tabele sa najviše upita', 1, 1),
    (11, 'Implementirati uloge i dozvole', 1, 2),
    (11, 'Planirati drugu fazu razvoja', 0, 1),
    (11, 'Dodati lenjo učitavanje slika', 1, 1),
    (11, 'Podesiti HTTPS i sertifikate', 2, 1),
    (11, 'Napraviti stranicu statusa sistema', 1, 1),
    (11, 'Napisati REST endpoint za detalje stavke', 0, 2),
    (11, 'Napraviti stranicu sa podešavanjima', 0, 0),
    (11, 'Dodati istoriju izmena za glavne entitete', 1, 0),
    (11, 'Podesiti CI/CD pipeline', 0, 1),
    (11, 'Postaviti Docker okruženje za razvoj', 0, 1),
    (12, 'Implementirati komentare na stavkama', 0, 2),
    (12, 'Napisati migracije za početnu šemu', 1, 2),
    (12, 'Napraviti stranicu sa uslovima korišćenja', 0, 0),
    (12, 'Dodati deljenje stavki putem linka', 2, 0),
    (12, 'Podesiti nadzor dostupnosti servisa', 2, 2),
    (12, 'Integrisati slanje e-pošte', 1, 2),
    (12, 'Napraviti stranicu statusa sistema', 1, 0),
    (12, 'Dodati filtere po kategoriji i datumu', 2, 2),
    (12, 'Dodati sinhronizaciju podataka između uređaja', 1, 2),
    (12, 'Implementirati višejezičnost', 1, 2),
    (12, 'Dodati uvoz podataka iz Excel fajla', 2, 2),
    (12, 'Dodati ocenjivanje i recenzije', 2, 1),
    (12, 'Napraviti stranicu profila korisnika', 2, 0),
    (12, 'Dodati lenjo učitavanje slika', 0, 1),
    (12, 'Implementirati zakazane zadatke u pozadini', 0, 0),
    (12, 'Održati radionicu za krajnje korisnike', 1, 0),
    (12, 'Proveriti kontrast boja prema WCAG smernicama', 2, 0),
    (12, 'Implementirati pretragu po ključnoj reči', 1, 1),
    (12, 'Dodati paginaciju i sortiranje na listu', 1, 1),
    (12, 'Sprovesti testiranje opterećenja', 1, 1),
    (12, 'Napraviti widget za brzi pregled', 0, 1),
    (12, 'Definisati korisničke priče i kriterijume prihvatanja', 1, 1),
    (12, 'Optimizovati spore SQL upite', 0, 0),
    (12, 'Implementirati izvoz podataka u CSV', 0, 0),
    (12, 'Nadograditi framework na najnoviju verziju', 1, 0),
    (13, 'Integrisati slanje e-pošte', 2, 0),
    (13, 'Implementirati offline režim rada', 1, 1),
    (13, 'Implementirati izvoz podataka u CSV', 1, 1),
    (13, 'Dodati audit log administratorskih akcija', 2, 0),
    (13, 'Implementirati dvofaktorsku prijavu', 1, 0),
    (13, 'Proveriti kontrast boja prema WCAG smernicama', 0, 0),
    (13, 'Napraviti stranicu sa podešavanjima', 2, 2),
    (13, 'Pregledati i zatvoriti stare tikete', 1, 1),
    (13, 'Planirati drugu fazu razvoja', 2, 0),
    (13, 'Napisati REST endpoint za listu stavki', 1, 0),
    (13, 'Dizajnirati šemu baze podataka', 0, 2),
    (13, 'Podesiti HTTPS i sertifikate', 0, 1),
    (13, 'Napraviti stranicu profila korisnika', 0, 1),
    (13, 'Validirati unos na serverskoj strani', 2, 0),
    (13, 'Dodati sinhronizaciju podataka između uređaja', 2, 2),
    (13, 'Podesiti nadzor dostupnosti servisa', 1, 0),
    (13, 'Optimizovati spore SQL upite', 0, 1),
    (13, 'Integrisati sa spoljnim servisom za plaćanje', 0, 2),
    (13, 'Implementirati responzivan prikaz za mobilne uređaje', 0, 1),
    (13, 'Sprovesti bezbednosni pregled zavisnosti', 2, 1),
    (13, 'Integrisati push obaveštenja', 1, 1),
    (13, 'Napraviti admin panel za upravljanje sadržajem', 0, 0),
    (13, 'Implementirati pretragu po ključnoj reči', 0, 2),
    (13, 'Validirati forme na klijentskoj strani', 2, 2),
    (13, 'Definisati korisničke priče i kriterijume prihvatanja', 0, 1),
    (14, 'Implementirati meko brisanje zapisa', 1, 0),
    (14, 'Dodati indekse na tabele sa najviše upita', 1, 2),
    (14, 'Snimiti video demonstraciju za prezentaciju', 1, 1),
    (14, 'Napraviti izveštaj o aktivnosti korisnika', 0, 2),
    (14, 'Napisati end-to-end testove za glavne tokove', 1, 0),
    (14, 'Integrisati sa spoljnim servisom za plaćanje', 0, 1),
    (14, 'Dodati istoriju izmena za glavne entitete', 2, 1),
    (14, 'Podesiti rezervne kopije baze', 2, 1),
    (14, 'Integrisati slanje e-pošte', 0, 2),
    (14, 'Dodati paginaciju i sortiranje na listu', 1, 1),
    (14, 'Dodati lenjo učitavanje slika', 1, 1),
    (14, 'Napisati migracije za početnu šemu', 2, 1),
    (14, 'Implementirati izvoz izveštaja u PDF', 1, 2),
    (14, 'Dodati uvoz podataka iz Excel fajla', 0, 1),
    (14, 'Dodati nedeljni pregled putem e-pošte', 2, 2),
    (14, 'Proveriti kontrast boja prema WCAG smernicama', 2, 1),
    (14, 'Napisati dokumentaciju API-ja', 2, 2),
    (14, 'Sprovesti bezbednosni pregled zavisnosti', 1, 1),
    (14, 'Implementirati QR kodove za brzi pristup', 2, 2),
    (14, 'Napisati REST endpoint za detalje stavke', 1, 0),
    (14, 'Podesiti logovanje i praćenje grešaka', 1, 1),
    (14, 'Dodati prečice na tastaturi', 2, 1),
    (14, 'Validirati unos na serverskoj strani', 2, 0),
    (14, 'Dodati zaštitu od prekomernog broja zahteva', 1, 1),
    (14, 'Smanjiti veličinu JavaScript bundle-a', 1, 2),
    (15, 'Dodati keširanje čestih upita', 0, 2),
    (15, 'Dodati uvoz podataka iz Excel fajla', 0, 0),
    (15, 'Integrisati push obaveštenja', 0, 0),
    (15, 'Implementirati SSO prijavu preko Google naloga', 1, 0),
    (15, 'Napraviti izveštaj o aktivnosti korisnika', 0, 2),
    (15, 'Poboljšati pristupačnost za čitače ekrana', 2, 1),
    (15, 'Integrisati sa spoljnim servisom za plaćanje', 1, 1),
    (15, 'Dodati tamnu temu', 0, 1),
    (15, 'Pripremiti produkciono okruženje', 0, 1),
    (15, 'Implementirati arhiviranje starih zapisa', 2, 0),
    (15, 'Dodati grafikone na kontrolnu tablu', 2, 2),
    (15, 'Implementirati višejezičnost', 0, 2),
    (15, 'Napisati migracije za početnu šemu', 0, 1),
    (15, 'Smanjiti veličinu JavaScript bundle-a', 0, 2),
    (15, 'Implementirati uloge i dozvole', 0, 0),
    (15, 'Napisati REST endpoint za detalje stavke', 1, 1),
    (15, 'Implementirati pretragu po ključnoj reči', 2, 1),
    (15, 'Nadograditi framework na najnoviju verziju', 0, 0),
    (15, 'Implementirati zakazane zadatke u pozadini', 1, 1),
    (15, 'Dodati filtere po kategoriji i datumu', 0, 1),
    (15, 'Održati radionicu za krajnje korisnike', 0, 2),
    (15, 'Podesiti HTTPS i sertifikate', 1, 2),
    (15, 'Implementirati offline režim rada', 0, 2),
    (15, 'Sprovesti testiranje opterećenja', 2, 1),
    (15, 'Napraviti stranicu statusa sistema', 0, 2),
    (16, 'Implementirati zakazane zadatke u pozadini', 2, 1),
    (16, 'Implementirati uloge i dozvole', 0, 1),
    (16, 'Napraviti widget za brzi pregled', 1, 2),
    (16, 'Napraviti izveštaj o aktivnosti korisnika', 0, 2),
    (16, 'Implementirati otpremanje fajlova', 0, 2),
    (16, 'Podesiti rezervne kopije baze', 1, 1),
    (16, 'Ispraviti greške prijavljene u beta testiranju', 0, 2),
    (16, 'Implementirati QR kodove za brzi pristup', 1, 1),
    (16, 'Implementirati komentare na stavkama', 0, 1),
    (16, 'Napisati skriptu za početne podatke', 1, 1),
    (16, 'Podesiti logovanje i praćenje grešaka', 0, 1),
    (16, 'Napraviti stranicu statusa sistema', 2, 1),
    (16, 'Napraviti kontrolnu tablu sa statistikom', 1, 1),
    (16, 'Dodati ocenjivanje i recenzije', 1, 1),
    (16, 'Sprovesti testiranje opterećenja', 2, 1),
    (16, 'Dodati indekse na tabele sa najviše upita', 0, 0),
    (16, 'Podesiti CI/CD pipeline', 1, 1),
    (16, 'Implementirati offline režim rada', 1, 1),
    (16, 'Ukloniti zastarele zavisnosti', 2, 0),
    (16, 'Održati radionicu za krajnje korisnike', 2, 2),
    (16, 'Dodati istoriju izmena za glavne entitete', 0, 1),
    (16, 'Napisati end-to-end testove za glavne tokove', 0, 1),
    (16, 'Podesiti red čekanja za obradu poruka', 2, 1),
    (16, 'Implementirati izvoz izveštaja u PDF', 0, 0),
    (16, 'Napraviti stranicu sa uslovima korišćenja', 0, 0),
    (17, 'Dodati kolačić baner i politiku privatnosti', 2, 1),
    (17, 'Napraviti izveštaj o aktivnosti korisnika', 2, 1),
    (17, 'Smanjiti veličinu JavaScript bundle-a', 2, 1),
    (17, 'Održati radionicu za krajnje korisnike', 0, 1),
    (17, 'Dodati paginaciju i sortiranje na listu', 2, 0),
    (17, 'Implementirati QR kodove za brzi pristup', 0, 0),
    (17, 'Optimizovati vreme učitavanja početne stranice', 1, 1),
    (17, 'Podesiti nadzor dostupnosti servisa', 2, 1),
    (17, 'Implementirati registraciju korisnika', 1, 2),
    (17, 'Dodati istoriju izmena za glavne entitete', 0, 2),
    (17, 'Validirati unos na serverskoj strani', 2, 1),
    (17, 'Podesiti red čekanja za obradu poruka', 0, 1),
    (17, 'Sprovesti testiranje opterećenja', 1, 0),
    (17, 'Podesiti logovanje i praćenje grešaka', 0, 2),
    (17, 'Implementirati pretragu po ključnoj reči', 1, 0),
    (17, 'Dodati zaboravljenu lozinku sa slanjem e-pošte', 0, 1),
    (17, 'Dodati ocenjivanje i recenzije', 0, 1),
    (17, 'Napraviti stranicu profila korisnika', 0, 2),
    (17, 'Dodati prečice na tastaturi', 0, 1),
    (17, 'Podesiti CI/CD pipeline', 0, 0),
    (17, 'Validirati forme na klijentskoj strani', 0, 0),
    (17, 'Napisati uputstvo za korisnike', 1, 0),
    (17, 'Napisati migracije za početnu šemu', 1, 1),
    (17, 'Implementirati brisanje naloga sa potvrdom', 1, 1),
    (17, 'Implementirati izvoz izveštaja u PDF', 2, 0),
    (18, 'Dodati grafikone na kontrolnu tablu', 0, 0),
    (18, 'Dodati lenjo učitavanje slika', 0, 2),
    (18, 'Dodati indekse na tabele sa najviše upita', 2, 0),
    (18, 'Dodati filtere po kategoriji i datumu', 0, 0),
    (18, 'Dodati prečice na tastaturi', 1, 1),
    (18, 'Ukloniti zastarele zavisnosti', 1, 0),
    (18, 'Dodati ocenjivanje i recenzije', 0, 2),
    (18, 'Integrisati sa spoljnim servisom za plaćanje', 2, 0),
    (18, 'Dodati kolačić baner i politiku privatnosti', 0, 2),
    (18, 'Pregledati i zatvoriti stare tikete', 0, 0),
    (18, 'Dodati deljenje stavki putem linka', 0, 1),
    (18, 'Integrisati push obaveštenja', 0, 1),
    (18, 'Implementirati QR kodove za brzi pristup', 0, 2),
    (18, 'Napraviti izveštaj o aktivnosti korisnika', 0, 1),
    (18, 'Dodati zaboravljenu lozinku sa slanjem e-pošte', 1, 1),
    (18, 'Validirati forme na klijentskoj strani', 0, 1),
    (18, 'Implementirati brisanje naloga sa potvrdom', 0, 1),
    (18, 'Optimizovati vreme učitavanja početne stranice', 1, 1),
    (18, 'Implementirati registraciju korisnika', 2, 1),
    (18, 'Podesiti HTTPS i sertifikate', 0, 1),
    (18, 'Napisati dokumentaciju API-ja', 0, 1),
    (18, 'Napraviti stranicu sa podešavanjima', 1, 0),
    (18, 'Napraviti widget za brzi pregled', 1, 1),
    (18, 'Podesiti CI/CD pipeline', 0, 2),
    (18, 'Održati radionicu za krajnje korisnike', 0, 1),
    (19, 'Dizajnirati šemu baze podataka', 0, 2),
    (19, 'Pripremiti produkciono okruženje', 1, 0),
    (19, 'Planirati drugu fazu razvoja', 2, 2),
    (19, 'Implementirati registraciju korisnika', 0, 0),
    (19, 'Podesiti red čekanja za obradu poruka', 1, 0),
    (19, 'Implementirati favorite i liste želja', 2, 0),
    (19, 'Postaviti Docker okruženje za razvoj', 2, 1),
    (19, 'Integrisati sa spoljnim servisom za plaćanje', 0, 1),
    (19, 'Napraviti glavnu navigaciju i layout', 2, 2),
    (19, 'Napraviti izveštaj o aktivnosti korisnika', 1, 1),
    (19, 'Proveriti kontrast boja prema WCAG smernicama', 1, 1),
    (19, 'Dodati filtere po kategoriji i datumu', 1, 2),
    (19, 'Napraviti stranicu sa uslovima korišćenja', 2, 0),
    (19, 'Dodati ocenjivanje i recenzije', 2, 1),
    (19, 'Implementirati otpremanje fajlova', 2, 1),
    (19, 'Napraviti widget za brzi pregled', 2, 1),
    (19, 'Optimizovati spore SQL upite', 0, 1),
    (19, 'Ispraviti greške prijavljene u beta testiranju', 0, 2),
    (19, 'Napisati dokumentaciju API-ja', 2, 1),
    (19, 'Implementirati izvoz izveštaja u PDF', 1, 1),
    (19, 'Napraviti stranicu sa podešavanjima', 2, 2),
    (19, 'Dodati uvoz podataka iz Excel fajla', 1, 2),
    (19, 'Održati radionicu za krajnje korisnike', 1, 1),
    (19, 'Nacrtati wireframe glavnih ekrana', 0, 2),
    (19, 'Implementirati prijavu sa JWT tokenom', 1, 1),
    (20, 'Dodati prečice na tastaturi', 1, 1),
    (20, 'Napraviti stranicu statusa sistema', 1, 1),
    (20, 'Implementirati arhiviranje starih zapisa', 2, 0),
    (20, 'Pripremiti produkciono okruženje', 2, 1),
    (20, 'Podesiti rezervne kopije baze', 0, 2),
    (20, 'Sprovesti testiranje opterećenja', 1, 1),
    (20, 'Napisati REST endpoint za listu stavki', 1, 0),
    (20, 'Dodati filtere po kategoriji i datumu', 1, 0),
    (20, 'Napraviti stranicu sa podešavanjima', 2, 2),
    (20, 'Napraviti izveštaj o aktivnosti korisnika', 0, 1),
    (20, 'Implementirati prijavu sa JWT tokenom', 0, 0),
    (20, 'Podesiti nadzor dostupnosti servisa', 0, 0),
    (20, 'Validirati unos na serverskoj strani', 2, 1),
    (20, 'Optimizovati spore SQL upite', 0, 2),
    (20, 'Sprovesti bezbednosni pregled zavisnosti', 1, 1),
    (20, 'Podesiti red čekanja za obradu poruka', 2, 0),
    (20, 'Napisati dokumentaciju API-ja', 1, 0),
    (20, 'Implementirati otpremanje fajlova', 0, 2),
    (20, 'Dodati kompresiju i promenu veličine slika', 1, 1),
    (20, 'Nacrtati wireframe glavnih ekrana', 1, 0),
    (20, 'Implementirati brisanje naloga sa potvrdom', 0, 1),
    (20, 'Integrisati slanje e-pošte', 2, 2),
    (20, 'Implementirati QR kodove za brzi pristup', 0, 0),
    (20, 'Dodati webhook obaveštenja za partnere', 0, 0),
    (20, 'Validirati forme na klijentskoj strani', 0, 1),
    (21, 'Implementirati registraciju korisnika', 0, 1),
    (21, 'Napisati skriptu za početne podatke', 2, 2),
    (21, 'Definisati korisničke priče i kriterijume prihvatanja', 2, 1),
    (21, 'Dodati nedeljni pregled putem e-pošte', 0, 1),
    (21, 'Implementirati izvoz izveštaja u PDF', 1, 1),
    (21, 'Ukloniti zastarele zavisnosti', 1, 1),
    (21, 'Implementirati zakazane zadatke u pozadini', 0, 2),
    (21, 'Nadograditi framework na najnoviju verziju', 0, 2),
    (21, 'Integrisati slanje e-pošte', 0, 1),
    (21, 'Dodati prečice na tastaturi', 2, 2),
    (21, 'Implementirati izvoz podataka u CSV', 1, 0),
    (21, 'Napisati uputstvo za korisnike', 0, 1),
    (21, 'Napisati REST endpoint za listu stavki', 2, 0),
    (21, 'Pripremiti produkciono okruženje', 1, 2),
    (21, 'Napraviti admin panel za upravljanje sadržajem', 1, 2),
    (21, 'Napisati REST endpoint za detalje stavke', 2, 2),
    (21, 'Implementirati dvofaktorsku prijavu', 1, 1),
    (21, 'Podesiti HTTPS i sertifikate', 0, 0),
    (21, 'Integrisati push obaveštenja', 2, 0),
    (21, 'Optimizovati spore SQL upite', 0, 2),
    (21, 'Postaviti Docker okruženje za razvoj', 2, 0),
    (21, 'Implementirati uloge i dozvole', 1, 2),
    (21, 'Validirati forme na klijentskoj strani', 1, 2),
    (21, 'Sprovesti testiranje opterećenja', 2, 1),
    (21, 'Napisati dokumentaciju API-ja', 0, 1),
    (22, 'Validirati forme na klijentskoj strani', 0, 1),
    (22, 'Dodati kompresiju i promenu veličine slika', 2, 1),
    (22, 'Dodati filtere po kategoriji i datumu', 0, 2),
    (22, 'Održati radionicu za krajnje korisnike', 2, 1),
    (22, 'Dodati tamnu temu', 0, 1),
    (22, 'Prevesti interfejs na engleski', 2, 1),
    (22, 'Implementirati otpremanje fajlova', 1, 1),
    (22, 'Napisati dokumentaciju API-ja', 1, 1),
    (22, 'Napisati end-to-end testove za glavne tokove', 0, 1),
    (22, 'Poboljšati pristupačnost za čitače ekrana', 1, 1),
    (22, 'Implementirati responzivan prikaz za mobilne uređaje', 2, 0),
    (22, 'Podesiti nadzor dostupnosti servisa', 1, 0),
    (22, 'Integrisati slanje e-pošte', 2, 1),
    (22, 'Napraviti widget za brzi pregled', 0, 1),
    (22, 'Napisati migracije za početnu šemu', 1, 0),
    (22, 'Integrisati push obaveštenja', 1, 1),
    (22, 'Nacrtati wireframe glavnih ekrana', 2, 0),
    (22, 'Napraviti stranicu statusa sistema', 1, 1),
    (22, 'Pregledati i zatvoriti stare tikete', 1, 0),
    (22, 'Napisati skriptu za početne podatke', 1, 1),
    (22, 'Implementirati favorite i liste želja', 1, 0),
    (22, 'Dodati ocenjivanje i recenzije', 0, 2),
    (22, 'Dodati sinhronizaciju podataka između uređaja', 0, 1),
    (22, 'Dodati istoriju izmena za glavne entitete', 0, 0),
    (22, 'Dodati zaboravljenu lozinku sa slanjem e-pošte', 1, 2),
    (23, 'Implementirati komentare na stavkama', 1, 2),
    (23, 'Poboljšati pristupačnost za čitače ekrana', 1, 2),
    (23, 'Implementirati favorite i liste želja', 0, 2),
    (23, 'Dodati zaštitu od prekomernog broja zahteva', 2, 0),
    (23, 'Implementirati izvoz izveštaja u PDF', 1, 0),
    (23, 'Implementirati otpremanje fajlova', 0, 1),
    (23, 'Napisati dokumentaciju API-ja', 1, 1),
    (23, 'Validirati unos na serverskoj strani', 0, 1),
    (23, 'Implementirati SSO prijavu preko Google naloga', 2, 1),
    (23, 'Dodati istoriju izmena za glavne entitete', 0, 1),
    (23, 'Nadograditi framework na najnoviju verziju', 0, 2),
    (23, 'Podesiti rezervne kopije baze', 2, 0),
    (23, 'Sprovesti bezbednosni pregled zavisnosti', 0, 0),
    (23, 'Podesiti CI/CD pipeline', 0, 0),
    (23, 'Dodati zaboravljenu lozinku sa slanjem e-pošte', 0, 1),
    (23, 'Implementirati izvoz podataka u CSV', 0, 1),
    (23, 'Dodati kolačić baner i politiku privatnosti', 0, 1),
    (23, 'Dodati filtere po kategoriji i datumu', 2, 2),
    (23, 'Implementirati registraciju korisnika', 2, 0),
    (23, 'Optimizovati vreme učitavanja početne stranice', 1, 2),
    (23, 'Pripremiti produkciono okruženje', 0, 0),
    (23, 'Dodati grafikone na kontrolnu tablu', 1, 1),
    (23, 'Implementirati QR kodove za brzi pristup', 0, 0),
    (23, 'Napraviti stranicu profila korisnika', 2, 1),
    (23, 'Dodati lenjo učitavanje slika', 2, 0),
    (24, 'Dodati uvoz podataka iz Excel fajla', 0, 2),
    (24, 'Podesiti nadzor dostupnosti servisa', 1, 0),
    (24, 'Prevesti interfejs na engleski', 2, 2),
    (24, 'Implementirati izvoz izveštaja u PDF', 2, 1),
    (24, 'Implementirati SSO prijavu preko Google naloga', 1, 1),
    (24, 'Optimizovati vreme učitavanja početne stranice', 0, 0),
    (24, 'Planirati drugu fazu razvoja', 2, 1),
    (24, 'Podesiti red čekanja za obradu poruka', 0, 1),
    (24, 'Poboljšati pristupačnost za čitače ekrana', 0, 0),
    (24, 'Postaviti Docker okruženje za razvoj', 0, 0),
    (24, 'Dodati istoriju izmena za glavne entitete', 1, 1),
    (24, 'Nacrtati wireframe glavnih ekrana', 1, 1),
    (24, 'Dodati kolačić baner i politiku privatnosti', 0, 1),
    (24, 'Napisati skriptu za početne podatke', 1, 0),
    (24, 'Integrisati slanje e-pošte', 1, 2),
    (24, 'Implementirati brisanje naloga sa potvrdom', 2, 1),
    (24, 'Dodati prečice na tastaturi', 0, 2),
    (24, 'Nadograditi framework na najnoviju verziju', 1, 0),
    (24, 'Sprovesti bezbednosni pregled zavisnosti', 2, 1),
    (24, 'Implementirati offline režim rada', 0, 0),
    (24, 'Implementirati responzivan prikaz za mobilne uređaje', 2, 1),
    (24, 'Dodati indekse na tabele sa najviše upita', 2, 2),
    (24, 'Validirati forme na klijentskoj strani', 1, 0),
    (24, 'Snimiti video demonstraciju za prezentaciju', 0, 0),
    (24, 'Pregledati i zatvoriti stare tikete', 2, 0),
    (25, 'Dodati prečice na tastaturi', 1, 2),
    (25, 'Definisati korisničke priče i kriterijume prihvatanja', 0, 1),
    (25, 'Dodati webhook obaveštenja za partnere', 1, 2),
    (25, 'Implementirati dvofaktorsku prijavu', 1, 0),
    (25, 'Pregledati i zatvoriti stare tikete', 0, 2),
    (25, 'Dodati audit log administratorskih akcija', 1, 2),
    (25, 'Dodati ocenjivanje i recenzije', 0, 0),
    (25, 'Prevesti interfejs na engleski', 0, 1),
    (25, 'Napraviti stranicu sa uslovima korišćenja', 0, 2),
    (25, 'Implementirati uloge i dozvole', 2, 0),
    (25, 'Napisati end-to-end testove za glavne tokove', 0, 2),
    (25, 'Implementirati meko brisanje zapisa', 0, 1),
    (25, 'Smanjiti veličinu JavaScript bundle-a', 2, 1),
    (25, 'Implementirati prijavu sa JWT tokenom', 0, 2),
    (25, 'Napraviti admin panel za upravljanje sadržajem', 1, 0),
    (25, 'Implementirati offline režim rada', 0, 2),
    (25, 'Napraviti stranicu statusa sistema', 0, 2),
    (25, 'Integrisati push obaveštenja', 0, 2),
    (25, 'Postaviti Docker okruženje za razvoj', 2, 0),
    (25, 'Optimizovati spore SQL upite', 2, 1),
    (25, 'Pripremiti produkciono okruženje', 0, 1),
    (25, 'Integrisati slanje e-pošte', 0, 1),
    (25, 'Napraviti kontrolnu tablu sa statistikom', 2, 1),
    (25, 'Podesiti CI/CD pipeline', 0, 0),
    (25, 'Dodati istoriju izmena za glavne entitete', 1, 2),
    (26, 'Dodati istoriju izmena za glavne entitete', 2, 1),
    (26, 'Implementirati meko brisanje zapisa', 0, 1),
    (26, 'Napisati uputstvo za korisnike', 2, 0),
    (26, 'Podesiti red čekanja za obradu poruka', 2, 0),
    (26, 'Dodati deljenje stavki putem linka', 2, 0),
    (26, 'Poboljšati pristupačnost za čitače ekrana', 1, 2),
    (26, 'Ukloniti zastarele zavisnosti', 1, 1),
    (26, 'Validirati forme na klijentskoj strani', 2, 1),
    (26, 'Podesiti HTTPS i sertifikate', 1, 0),
    (26, 'Integrisati push obaveštenja', 0, 1),
    (26, 'Dodati zaboravljenu lozinku sa slanjem e-pošte', 2, 1),
    (26, 'Optimizovati vreme učitavanja početne stranice', 1, 1),
    (26, 'Napraviti widget za brzi pregled', 1, 1),
    (26, 'Podesiti CI/CD pipeline', 0, 0),
    (26, 'Implementirati izvoz izveštaja u PDF', 2, 0),
    (26, 'Dodati uvoz podataka iz Excel fajla', 0, 1),
    (26, 'Integrisati slanje e-pošte', 0, 2),
    (26, 'Napraviti stranicu profila korisnika', 0, 0),
    (26, 'Validirati unos na serverskoj strani', 1, 2),
    (26, 'Pripremiti produkciono okruženje', 0, 2),
    (26, 'Implementirati zakazane zadatke u pozadini', 1, 2),
    (26, 'Implementirati arhiviranje starih zapisa', 2, 1),
    (26, 'Sprovesti testiranje opterećenja', 0, 2),
    (26, 'Dodati tamnu temu', 0, 1),
    (26, 'Implementirati SSO prijavu preko Google naloga', 0, 1),
    (27, 'Implementirati brisanje naloga sa potvrdom', 1, 2),
    (27, 'Smanjiti veličinu JavaScript bundle-a', 2, 1),
    (27, 'Implementirati pretragu po ključnoj reči', 2, 2),
    (27, 'Definisati korisničke priče i kriterijume prihvatanja', 0, 0),
    (27, 'Ukloniti zastarele zavisnosti', 0, 1),
    (27, 'Implementirati izvoz izveštaja u PDF', 1, 1),
    (27, 'Dodati keširanje čestih upita', 0, 1),
    (27, 'Dodati zaboravljenu lozinku sa slanjem e-pošte', 0, 0),
    (27, 'Implementirati višejezičnost', 1, 1),
    (27, 'Ispraviti greške prijavljene u beta testiranju', 1, 1),
    (27, 'Postaviti Docker okruženje za razvoj', 2, 1),
    (27, 'Implementirati otpremanje fajlova', 2, 2),
    (27, 'Napisati migracije za početnu šemu', 2, 1),
    (27, 'Dodati lenjo učitavanje slika', 1, 2),
    (27, 'Implementirati izvoz podataka u CSV', 1, 0),
    (27, 'Planirati drugu fazu razvoja', 1, 0),
    (27, 'Implementirati arhiviranje starih zapisa', 0, 0),
    (27, 'Napraviti stranicu profila korisnika', 0, 1),
    (27, 'Dodati zaštitu od prekomernog broja zahteva', 0, 1),
    (27, 'Sprovesti testiranje opterećenja', 1, 1),
    (27, 'Napraviti izveštaj o aktivnosti korisnika', 0, 2),
    (27, 'Nacrtati wireframe glavnih ekrana', 0, 1),
    (27, 'Nadograditi framework na najnoviju verziju', 2, 0),
    (27, 'Implementirati prijavu sa JWT tokenom', 1, 0),
    (27, 'Napraviti admin panel za upravljanje sadržajem', 1, 0),
    (28, 'Dodati kompresiju i promenu veličine slika', 0, 1),
    (28, 'Dodati deljenje stavki putem linka', 2, 0),
    (28, 'Dodati audit log administratorskih akcija', 1, 0),
    (28, 'Postaviti Docker okruženje za razvoj', 0, 1),
    (28, 'Prevesti interfejs na engleski', 1, 1),
    (28, 'Implementirati višejezičnost', 1, 1),
    (28, 'Dodati kolačić baner i politiku privatnosti', 0, 1),
    (28, 'Podesiti nadzor dostupnosti servisa', 2, 0),
    (28, 'Napraviti stranicu sa uslovima korišćenja', 0, 1),
    (28, 'Pripremiti produkciono okruženje', 1, 1),
    (28, 'Validirati forme na klijentskoj strani', 0, 0),
    (28, 'Sprovesti bezbednosni pregled zavisnosti', 2, 1),
    (28, 'Napraviti kontrolnu tablu sa statistikom', 1, 1),
    (28, 'Optimizovati vreme učitavanja početne stranice', 0, 0),
    (28, 'Pregledati i zatvoriti stare tikete', 1, 2),
    (28, 'Dodati ocenjivanje i recenzije', 0, 1),
    (28, 'Nadograditi framework na najnoviju verziju', 2, 2),
    (28, 'Napraviti stranicu profila korisnika', 0, 2),
    (28, 'Napraviti izveštaj o aktivnosti korisnika', 0, 2),
    (28, 'Sprovesti testiranje opterećenja', 2, 1),
    (28, 'Dodati uvoz podataka iz Excel fajla', 0, 2),
    (28, 'Implementirati otpremanje fajlova', 0, 0),
    (28, 'Napisati migracije za početnu šemu', 2, 1),
    (28, 'Podesiti HTTPS i sertifikate', 2, 2),
    (28, 'Implementirati izvoz podataka u CSV', 1, 2),
    (29, 'Implementirati arhiviranje starih zapisa', 1, 2),
    (29, 'Implementirati prijavu sa JWT tokenom', 1, 2),
    (29, 'Snimiti video demonstraciju za prezentaciju', 1, 1),
    (29, 'Podesiti HTTPS i sertifikate', 1, 1),
    (29, 'Prevesti interfejs na engleski', 2, 1),
    (29, 'Napisati uputstvo za korisnike', 1, 1),
    (29, 'Optimizovati vreme učitavanja početne stranice', 1, 1),
    (29, 'Implementirati pretragu po ključnoj reči', 0, 1),
    (29, 'Napraviti admin panel za upravljanje sadržajem', 1, 1),
    (29, 'Napraviti glavnu navigaciju i layout', 2, 1),
    (29, 'Napraviti stranicu sa podešavanjima', 0, 1),
    (29, 'Dodati prečice na tastaturi', 0, 1),
    (29, 'Proveriti kontrast boja prema WCAG smernicama', 0, 2),
    (29, 'Dodati istoriju izmena za glavne entitete', 1, 0),
    (29, 'Napraviti stranicu profila korisnika', 2, 2),
    (29, 'Integrisati slanje e-pošte', 1, 2),
    (29, 'Dodati deljenje stavki putem linka', 1, 1),
    (29, 'Nacrtati wireframe glavnih ekrana', 1, 1),
    (29, 'Napraviti kontrolnu tablu sa statistikom', 1, 1),
    (29, 'Dodati audit log administratorskih akcija', 0, 1),
    (29, 'Dodati kompresiju i promenu veličine slika', 0, 2),
    (29, 'Implementirati dvofaktorsku prijavu', 2, 1),
    (29, 'Validirati unos na serverskoj strani', 1, 0),
    (29, 'Dodati zaštitu od prekomernog broja zahteva', 2, 0),
    (29, 'Napisati end-to-end testove za glavne tokove', 1, 0),
    (30, 'Validirati forme na klijentskoj strani', 1, 0),
    (30, 'Nacrtati wireframe glavnih ekrana', 0, 2),
    (30, 'Napraviti stranicu profila korisnika', 0, 2),
    (30, 'Dodati sinhronizaciju podataka između uređaja', 0, 1),
    (30, 'Napisati REST endpoint za listu stavki', 1, 2),
    (30, 'Napisati uputstvo za korisnike', 0, 1),
    (30, 'Integrisati slanje e-pošte', 2, 2),
    (30, 'Pregledati i zatvoriti stare tikete', 0, 2),
    (30, 'Implementirati QR kodove za brzi pristup', 2, 0),
    (30, 'Implementirati registraciju korisnika', 0, 0),
    (30, 'Implementirati izvoz izveštaja u PDF', 0, 0),
    (30, 'Sprovesti bezbednosni pregled zavisnosti', 1, 1),
    (30, 'Održati radionicu za krajnje korisnike', 0, 1),
    (30, 'Implementirati dvofaktorsku prijavu', 2, 1),
    (30, 'Podesiti CI/CD pipeline', 0, 0),
    (30, 'Podesiti rezervne kopije baze', 2, 0),
    (30, 'Napraviti stranicu statusa sistema', 0, 0),
    (30, 'Postaviti Docker okruženje za razvoj', 2, 1),
    (30, 'Integrisati sa spoljnim servisom za plaćanje', 2, 2),
    (30, 'Implementirati SSO prijavu preko Google naloga', 2, 2),
    (30, 'Planirati drugu fazu razvoja', 1, 0),
    (30, 'Dodati audit log administratorskih akcija', 0, 1),
    (30, 'Napraviti widget za brzi pregled', 0, 2),
    (30, 'Implementirati meko brisanje zapisa', 0, 0),
    (30, 'Integrisati push obaveštenja', 0, 2),
    (31, 'Integrisati push obaveštenja', 0, 1),
    (31, 'Podesiti nadzor dostupnosti servisa', 0, 0),
    (31, 'Dodati tamnu temu', 1, 0),
    (31, 'Napisati skriptu za početne podatke', 2, 1),
    (31, 'Implementirati izvoz izveštaja u PDF', 1, 1),
    (31, 'Dodati filtere po kategoriji i datumu', 2, 0),
    (31, 'Implementirati meko brisanje zapisa', 1, 2),
    (31, 'Dodati uvoz podataka iz Excel fajla', 1, 0),
    (31, 'Implementirati izvoz podataka u CSV', 2, 1),
    (31, 'Implementirati dvofaktorsku prijavu', 2, 1),
    (31, 'Napraviti widget za brzi pregled', 0, 2),
    (31, 'Napisati REST endpoint za listu stavki', 1, 0),
    (31, 'Implementirati arhiviranje starih zapisa', 1, 0),
    (31, 'Podesiti red čekanja za obradu poruka', 2, 1),
    (31, 'Implementirati komentare na stavkama', 1, 2),
    (31, 'Napisati REST endpoint za detalje stavke', 0, 1),
    (31, 'Dodati istoriju izmena za glavne entitete', 0, 1),
    (31, 'Dodati zaštitu od prekomernog broja zahteva', 0, 2),
    (31, 'Integrisati sa spoljnim servisom za plaćanje', 1, 0),
    (31, 'Implementirati brisanje naloga sa potvrdom', 2, 1),
    (31, 'Dodati lenjo učitavanje slika', 1, 1),
    (31, 'Napraviti stranicu profila korisnika', 0, 2),
    (31, 'Sprovesti bezbednosni pregled zavisnosti', 2, 1),
    (31, 'Prevesti interfejs na engleski', 0, 0),
    (31, 'Implementirati QR kodove za brzi pristup', 2, 1),
    (32, 'Podesiti logovanje i praćenje grešaka', 2, 1),
    (32, 'Implementirati registraciju korisnika', 0, 1),
    (32, 'Integrisati slanje e-pošte', 1, 0),
    (32, 'Implementirati responzivan prikaz za mobilne uređaje', 0, 1),
    (32, 'Proveriti kontrast boja prema WCAG smernicama', 0, 1),
    (32, 'Implementirati dvofaktorsku prijavu', 1, 2),
    (32, 'Dodati indekse na tabele sa najviše upita', 0, 2),
    (32, 'Implementirati QR kodove za brzi pristup', 1, 1),
    (32, 'Podesiti CI/CD pipeline', 1, 1),
    (32, 'Podesiti nadzor dostupnosti servisa', 2, 1),
    (32, 'Dodati ocenjivanje i recenzije', 2, 1),
    (32, 'Dodati deljenje stavki putem linka', 1, 2),
    (32, 'Ukloniti zastarele zavisnosti', 0, 1),
    (32, 'Napisati dokumentaciju API-ja', 1, 1),
    (32, 'Dodati keširanje čestih upita', 0, 0),
    (32, 'Dodati audit log administratorskih akcija', 0, 1),
    (32, 'Dodati kompresiju i promenu veličine slika', 2, 1),
    (32, 'Implementirati izvoz izveštaja u PDF', 0, 1),
    (32, 'Definisati korisničke priče i kriterijume prihvatanja', 2, 0),
    (32, 'Implementirati zakazane zadatke u pozadini', 1, 0),
    (32, 'Optimizovati vreme učitavanja početne stranice', 1, 1),
    (32, 'Ispraviti greške prijavljene u beta testiranju', 0, 1),
    (32, 'Implementirati pretragu po ključnoj reči', 1, 1),
    (32, 'Validirati unos na serverskoj strani', 0, 0),
    (32, 'Napraviti stranicu profila korisnika', 2, 2),
    (33, 'Napraviti kontrolnu tablu sa statistikom', 0, 0),
    (33, 'Implementirati dvofaktorsku prijavu', 0, 1),
    (33, 'Integrisati sa spoljnim servisom za plaćanje', 2, 0),
    (33, 'Sprovesti bezbednosni pregled zavisnosti', 0, 0),
    (33, 'Dodati keširanje čestih upita', 1, 1),
    (33, 'Održati radionicu za krajnje korisnike', 0, 0),
    (33, 'Podesiti CI/CD pipeline', 1, 0),
    (33, 'Ukloniti zastarele zavisnosti', 2, 0),
    (33, 'Dodati grafikone na kontrolnu tablu', 0, 2),
    (33, 'Napisati migracije za početnu šemu', 0, 1),
    (33, 'Dodati audit log administratorskih akcija', 1, 1),
    (33, 'Nacrtati wireframe glavnih ekrana', 2, 1),
    (33, 'Dodati sinhronizaciju podataka između uređaja', 2, 2),
    (33, 'Implementirati registraciju korisnika', 0, 1),
    (33, 'Optimizovati vreme učitavanja početne stranice', 2, 0),
    (33, 'Dodati prečice na tastaturi', 2, 1),
    (33, 'Dodati tamnu temu', 1, 1),
    (33, 'Snimiti video demonstraciju za prezentaciju', 0, 0),
    (33, 'Planirati drugu fazu razvoja', 0, 1),
    (33, 'Napisati dokumentaciju API-ja', 0, 2),
    (33, 'Validirati unos na serverskoj strani', 1, 1),
    (33, 'Sprovesti testiranje opterećenja', 0, 0),
    (33, 'Napraviti stranicu sa podešavanjima', 0, 0),
    (33, 'Implementirati favorite i liste želja', 2, 1),
    (33, 'Dodati lenjo učitavanje slika', 0, 1),
    (34, 'Dodati prečice na tastaturi', 1, 0),
    (34, 'Implementirati meko brisanje zapisa', 0, 1),
    (34, 'Dodati kompresiju i promenu veličine slika', 2, 1),
    (34, 'Snimiti video demonstraciju za prezentaciju', 1, 0),
    (34, 'Implementirati favorite i liste želja', 0, 0),
    (34, 'Refaktorisati servisni sloj', 1, 0),
    (34, 'Implementirati arhiviranje starih zapisa', 1, 1),
    (34, 'Dodati keširanje čestih upita', 2, 2),
    (34, 'Napraviti admin panel za upravljanje sadržajem', 0, 1),
    (34, 'Pripremiti produkciono okruženje', 1, 0),
    (34, 'Dodati audit log administratorskih akcija', 2, 2),
    (34, 'Implementirati komentare na stavkama', 0, 0),
    (34, 'Dodati filtere po kategoriji i datumu', 2, 0),
    (34, 'Planirati drugu fazu razvoja', 1, 2),
    (34, 'Održati radionicu za krajnje korisnike', 0, 1),
    (34, 'Dodati deljenje stavki putem linka', 0, 0),
    (34, 'Implementirati prijavu sa JWT tokenom', 0, 1),
    (34, 'Dodati grafikone na kontrolnu tablu', 2, 1),
    (34, 'Dodati istoriju izmena za glavne entitete', 0, 0),
    (34, 'Validirati unos na serverskoj strani', 0, 1),
    (34, 'Smanjiti veličinu JavaScript bundle-a', 1, 1),
    (34, 'Pregledati i zatvoriti stare tikete', 1, 0),
    (34, 'Podesiti rezervne kopije baze', 1, 1),
    (34, 'Sprovesti testiranje opterećenja', 2, 1),
    (34, 'Dodati webhook obaveštenja za partnere', 0, 0),
    (35, 'Dodati webhook obaveštenja za partnere', 2, 1),
    (35, 'Podesiti HTTPS i sertifikate', 1, 1),
    (35, 'Napisati REST endpoint za listu stavki', 1, 1),
    (35, 'Napraviti kontrolnu tablu sa statistikom', 0, 1),
    (35, 'Napraviti admin panel za upravljanje sadržajem', 2, 1),
    (35, 'Dodati tamnu temu', 1, 0),
    (35, 'Implementirati višejezičnost', 0, 1),
    (35, 'Nadograditi framework na najnoviju verziju', 2, 1),
    (35, 'Sprovesti bezbednosni pregled zavisnosti', 1, 2),
    (35, 'Ispraviti greške prijavljene u beta testiranju', 0, 2),
    (35, 'Implementirati QR kodove za brzi pristup', 0, 1),
    (35, 'Implementirati pretragu po ključnoj reči', 2, 1),
    (35, 'Napisati uputstvo za korisnike', 2, 2),
    (35, 'Napisati skriptu za početne podatke', 0, 1),
    (35, 'Podesiti red čekanja za obradu poruka', 0, 1),
    (35, 'Validirati unos na serverskoj strani', 1, 1),
    (35, 'Sprovesti testiranje opterećenja', 0, 1),
    (35, 'Postaviti Docker okruženje za razvoj', 2, 1),
    (35, 'Implementirati registraciju korisnika', 1, 1),
    (35, 'Implementirati uloge i dozvole', 1, 1),
    (35, 'Validirati forme na klijentskoj strani', 1, 1),
    (35, 'Implementirati prijavu sa JWT tokenom', 2, 1),
    (35, 'Integrisati push obaveštenja', 0, 0),
    (35, 'Dodati prečice na tastaturi', 0, 2),
    (35, 'Dodati grafikone na kontrolnu tablu', 1, 2),
    (36, 'Implementirati meko brisanje zapisa', 0, 0),
    (36, 'Nacrtati wireframe glavnih ekrana', 0, 0),
    (36, 'Implementirati responzivan prikaz za mobilne uređaje', 2, 1),
    (36, 'Podesiti HTTPS i sertifikate', 1, 2),
    (36, 'Integrisati slanje e-pošte', 0, 0),
    (36, 'Napisati REST endpoint za detalje stavke', 1, 2),
    (36, 'Dodati sinhronizaciju podataka između uređaja', 1, 0),
    (36, 'Ispraviti greške prijavljene u beta testiranju', 0, 1),
    (36, 'Postaviti Docker okruženje za razvoj', 2, 0),
    (36, 'Dodati webhook obaveštenja za partnere', 1, 1),
    (36, 'Pripremiti produkciono okruženje', 1, 1),
    (36, 'Optimizovati spore SQL upite', 0, 1),
    (36, 'Optimizovati vreme učitavanja početne stranice', 0, 1),
    (36, 'Napraviti izveštaj o aktivnosti korisnika', 1, 2),
    (36, 'Podesiti rezervne kopije baze', 2, 1),
    (36, 'Dodati uvoz podataka iz Excel fajla', 0, 0),
    (36, 'Refaktorisati servisni sloj', 1, 2),
    (36, 'Implementirati pretragu po ključnoj reči', 1, 2),
    (36, 'Implementirati QR kodove za brzi pristup', 2, 0),
    (36, 'Dodati istoriju izmena za glavne entitete', 2, 1),
    (36, 'Integrisati sa spoljnim servisom za plaćanje', 2, 0),
    (36, 'Implementirati registraciju korisnika', 0, 1),
    (36, 'Snimiti video demonstraciju za prezentaciju', 2, 0),
    (36, 'Napisati end-to-end testove za glavne tokove', 0, 2),
    (36, 'Napraviti admin panel za upravljanje sadržajem', 0, 1),
    (37, 'Dodati prečice na tastaturi', 2, 1),
    (37, 'Implementirati arhiviranje starih zapisa', 2, 2),
    (37, 'Napisati REST endpoint za detalje stavke', 1, 2),
    (37, 'Pripremiti produkciono okruženje', 0, 1),
    (37, 'Integrisati push obaveštenja', 1, 1),
    (37, 'Napraviti stranicu profila korisnika', 0, 0),
    (37, 'Dizajnirati šemu baze podataka', 1, 0),
    (37, 'Implementirati otpremanje fajlova', 2, 0),
    (37, 'Dodati audit log administratorskih akcija', 1, 1),
    (37, 'Implementirati pretragu po ključnoj reči', 0, 1),
    (37, 'Implementirati prijavu sa JWT tokenom', 0, 2),
    (37, 'Dodati keširanje čestih upita', 2, 1),
    (37, 'Sprovesti bezbednosni pregled zavisnosti', 0, 0),
    (37, 'Napraviti kontrolnu tablu sa statistikom', 2, 0),
    (37, 'Implementirati brisanje naloga sa potvrdom', 2, 1),
    (37, 'Dodati webhook obaveštenja za partnere', 1, 1),
    (37, 'Nadograditi framework na najnoviju verziju', 2, 0),
    (37, 'Snimiti video demonstraciju za prezentaciju', 0, 2),
    (37, 'Dodati kolačić baner i politiku privatnosti', 0, 2),
    (37, 'Implementirati izvoz podataka u CSV', 0, 0),
    (37, 'Podesiti CI/CD pipeline', 1, 0),
    (37, 'Podesiti nadzor dostupnosti servisa', 2, 2),
    (37, 'Napraviti stranicu sa uslovima korišćenja', 0, 1),
    (37, 'Postaviti Docker okruženje za razvoj', 2, 0),
    (37, 'Napisati REST endpoint za listu stavki', 0, 0),
    (38, 'Dodati nedeljni pregled putem e-pošte', 0, 2),
    (38, 'Implementirati registraciju korisnika', 0, 1),
    (38, 'Prevesti interfejs na engleski', 0, 0),
    (38, 'Dodati prečice na tastaturi', 1, 1),
    (38, 'Ispraviti greške prijavljene u beta testiranju', 0, 1),
    (38, 'Implementirati pretragu po ključnoj reči', 1, 1),
    (38, 'Napraviti glavnu navigaciju i layout', 2, 0),
    (38, 'Nacrtati wireframe glavnih ekrana', 0, 2),
    (38, 'Sprovesti bezbednosni pregled zavisnosti', 0, 1),
    (38, 'Dodati zaštitu od prekomernog broja zahteva', 1, 1),
    (38, 'Dodati sinhronizaciju podataka između uređaja', 1, 1),
    (38, 'Podesiti logovanje i praćenje grešaka', 0, 2),
    (38, 'Implementirati responzivan prikaz za mobilne uređaje', 2, 0),
    (38, 'Dodati lenjo učitavanje slika', 1, 1),
    (38, 'Validirati unos na serverskoj strani', 0, 2),
    (38, 'Dodati deljenje stavki putem linka', 0, 0),
    (38, 'Dizajnirati šemu baze podataka', 1, 2),
    (38, 'Napraviti admin panel za upravljanje sadržajem', 0, 2),
    (38, 'Nadograditi framework na najnoviju verziju', 2, 0),
    (38, 'Napisati REST endpoint za listu stavki', 2, 1),
    (38, 'Dodati indekse na tabele sa najviše upita', 1, 1),
    (38, 'Napisati end-to-end testove za glavne tokove', 0, 2),
    (38, 'Dodati kolačić baner i politiku privatnosti', 1, 2),
    (38, 'Snimiti video demonstraciju za prezentaciju', 2, 2),
    (38, 'Implementirati izvoz izveštaja u PDF', 1, 2),
    (39, 'Napraviti widget za brzi pregled', 0, 1),
    (39, 'Dodati ocenjivanje i recenzije', 0, 2),
    (39, 'Poboljšati pristupačnost za čitače ekrana', 2, 0),
    (39, 'Dodati filtere po kategoriji i datumu', 2, 1),
    (39, 'Implementirati QR kodove za brzi pristup', 2, 1),
    (39, 'Sprovesti bezbednosni pregled zavisnosti', 2, 2),
    (39, 'Dodati grafikone na kontrolnu tablu', 1, 0),
    (39, 'Implementirati registraciju korisnika', 0, 1),
    (39, 'Implementirati favorite i liste želja', 1, 0),
    (39, 'Implementirati dvofaktorsku prijavu', 0, 1),
    (39, 'Dodati kolačić baner i politiku privatnosti', 0, 2),
    (39, 'Napraviti glavnu navigaciju i layout', 0, 0),
    (39, 'Refaktorisati servisni sloj', 1, 1),
    (39, 'Dodati paginaciju i sortiranje na listu', 1, 2),
    (39, 'Implementirati uloge i dozvole', 0, 1),
    (39, 'Implementirati pretragu po ključnoj reči', 1, 2),
    (39, 'Napisati end-to-end testove za glavne tokove', 0, 1),
    (39, 'Implementirati arhiviranje starih zapisa', 0, 0),
    (39, 'Implementirati SSO prijavu preko Google naloga', 0, 2),
    (39, 'Validirati forme na klijentskoj strani', 1, 0),
    (39, 'Implementirati zakazane zadatke u pozadini', 2, 1),
    (39, 'Implementirati otpremanje fajlova', 0, 2),
    (39, 'Podesiti CI/CD pipeline', 2, 2),
    (39, 'Pregledati i zatvoriti stare tikete', 0, 1),
    (39, 'Napraviti stranicu sa uslovima korišćenja', 0, 1),
    (40, 'Pregledati i zatvoriti stare tikete', 0, 1),
    (40, 'Podesiti logovanje i praćenje grešaka', 0, 1),
    (40, 'Implementirati dvofaktorsku prijavu', 1, 1),
    (40, 'Podesiti CI/CD pipeline', 0, 1),
    (40, 'Dodati zaboravljenu lozinku sa slanjem e-pošte', 0, 1),
    (40, 'Dodati sinhronizaciju podataka između uređaja', 1, 0),
    (40, 'Dodati paginaciju i sortiranje na listu', 2, 0),
    (40, 'Implementirati komentare na stavkama', 2, 1),
    (40, 'Dodati prečice na tastaturi', 0, 1),
    (40, 'Podesiti rezervne kopije baze', 0, 1),
    (40, 'Napraviti glavnu navigaciju i layout', 0, 2),
    (40, 'Implementirati prijavu sa JWT tokenom', 0, 1),
    (40, 'Postaviti Docker okruženje za razvoj', 1, 2),
    (40, 'Optimizovati spore SQL upite', 2, 0),
    (40, 'Dodati istoriju izmena za glavne entitete', 1, 2),
    (40, 'Proveriti kontrast boja prema WCAG smernicama', 0, 1),
    (40, 'Napraviti stranicu statusa sistema', 0, 1),
    (40, 'Napraviti stranicu sa podešavanjima', 2, 2),
    (40, 'Implementirati responzivan prikaz za mobilne uređaje', 0, 2),
    (40, 'Definisati korisničke priče i kriterijume prihvatanja', 0, 1),
    (40, 'Implementirati izvoz podataka u CSV', 1, 0),
    (40, 'Napisati skriptu za početne podatke', 0, 0),
    (40, 'Refaktorisati servisni sloj', 0, 2),
    (40, 'Održati radionicu za krajnje korisnike', 0, 1),
    (40, 'Dodati grafikone na kontrolnu tablu', 0, 0),
    (41, 'Podesiti CI/CD pipeline', 0, 0),
    (41, 'Dodati nedeljni pregled putem e-pošte', 2, 0),
    (41, 'Implementirati offline režim rada', 0, 2),
    (41, 'Implementirati pretragu po ključnoj reči', 2, 0),
    (41, 'Podesiti nadzor dostupnosti servisa', 2, 2),
    (41, 'Ispraviti greške prijavljene u beta testiranju', 0, 1),
    (41, 'Dodati deljenje stavki putem linka', 1, 1),
    (41, 'Dodati zaštitu od prekomernog broja zahteva', 0, 2),
    (41, 'Implementirati izvoz izveštaja u PDF', 0, 2),
    (41, 'Poboljšati pristupačnost za čitače ekrana', 0, 0),
    (41, 'Pregledati i zatvoriti stare tikete', 0, 0),
    (41, 'Prevesti interfejs na engleski', 2, 1),
    (41, 'Nadograditi framework na najnoviju verziju', 0, 1),
    (41, 'Dodati filtere po kategoriji i datumu', 0, 2),
    (41, 'Dodati uvoz podataka iz Excel fajla', 0, 2),
    (41, 'Integrisati push obaveštenja', 0, 0),
    (41, 'Dodati kompresiju i promenu veličine slika', 0, 0),
    (41, 'Dodati ocenjivanje i recenzije', 1, 0),
    (41, 'Napraviti stranicu sa uslovima korišćenja', 1, 0),
    (41, 'Sprovesti testiranje opterećenja', 0, 0),
    (41, 'Implementirati SSO prijavu preko Google naloga', 1, 1),
    (41, 'Dodati kolačić baner i politiku privatnosti', 0, 0),
    (41, 'Napisati REST endpoint za detalje stavke', 2, 1),
    (41, 'Održati radionicu za krajnje korisnike', 1, 1),
    (41, 'Implementirati brisanje naloga sa potvrdom', 2, 1),
    (42, 'Implementirati prijavu sa JWT tokenom', 0, 1),
    (42, 'Dodati keširanje čestih upita', 0, 1),
    (42, 'Prevesti interfejs na engleski', 0, 1),
    (42, 'Nadograditi framework na najnoviju verziju', 0, 1),
    (42, 'Implementirati brisanje naloga sa potvrdom', 0, 1),
    (42, 'Implementirati višejezičnost', 1, 1),
    (42, 'Dodati istoriju izmena za glavne entitete', 1, 1),
    (42, 'Pripremiti produkciono okruženje', 0, 1),
    (42, 'Implementirati responzivan prikaz za mobilne uređaje', 0, 1),
    (42, 'Napisati end-to-end testove za glavne tokove', 1, 2),
    (42, 'Dodati audit log administratorskih akcija', 0, 0),
    (42, 'Implementirati dvofaktorsku prijavu', 1, 2),
    (42, 'Održati radionicu za krajnje korisnike', 0, 0),
    (42, 'Validirati unos na serverskoj strani', 1, 2),
    (42, 'Implementirati pretragu po ključnoj reči', 0, 1),
    (42, 'Implementirati izvoz izveštaja u PDF', 2, 0),
    (42, 'Implementirati registraciju korisnika', 2, 0),
    (42, 'Implementirati zakazane zadatke u pozadini', 2, 1),
    (42, 'Dodati paginaciju i sortiranje na listu', 1, 1),
    (42, 'Ispraviti greške prijavljene u beta testiranju', 1, 0),
    (42, 'Dodati sinhronizaciju podataka između uređaja', 1, 1),
    (42, 'Dodati deljenje stavki putem linka', 1, 2),
    (42, 'Implementirati komentare na stavkama', 2, 0),
    (42, 'Ukloniti zastarele zavisnosti', 1, 1),
    (42, 'Implementirati arhiviranje starih zapisa', 0, 1),
    (43, 'Podesiti red čekanja za obradu poruka', 2, 2),
    (43, 'Integrisati slanje e-pošte', 0, 2),
    (43, 'Validirati forme na klijentskoj strani', 2, 0),
    (43, 'Napraviti stranicu statusa sistema', 2, 1),
    (43, 'Dodati zaštitu od prekomernog broja zahteva', 0, 0),
    (43, 'Dodati grafikone na kontrolnu tablu', 2, 1),
    (43, 'Dodati deljenje stavki putem linka', 1, 1),
    (43, 'Pregledati i zatvoriti stare tikete', 2, 1),
    (43, 'Implementirati komentare na stavkama', 1, 2),
    (43, 'Implementirati arhiviranje starih zapisa', 0, 1),
    (43, 'Implementirati izvoz podataka u CSV', 0, 0),
    (43, 'Napraviti kontrolnu tablu sa statistikom', 1, 0),
    (43, 'Ukloniti zastarele zavisnosti', 2, 1),
    (43, 'Prevesti interfejs na engleski', 2, 1),
    (43, 'Dodati uvoz podataka iz Excel fajla', 0, 2),
    (43, 'Dodati paginaciju i sortiranje na listu', 0, 1),
    (43, 'Implementirati registraciju korisnika', 0, 1),
    (43, 'Implementirati dvofaktorsku prijavu', 1, 0),
    (43, 'Napisati REST endpoint za detalje stavke', 1, 0),
    (43, 'Dodati zaboravljenu lozinku sa slanjem e-pošte', 1, 1),
    (43, 'Napisati uputstvo za korisnike', 0, 0),
    (43, 'Nacrtati wireframe glavnih ekrana', 1, 1),
    (43, 'Implementirati QR kodove za brzi pristup', 0, 1),
    (43, 'Održati radionicu za krajnje korisnike', 2, 0),
    (43, 'Optimizovati spore SQL upite', 0, 1),
    (44, 'Dodati sinhronizaciju podataka između uređaja', 1, 1),
    (44, 'Optimizovati spore SQL upite', 0, 2),
    (44, 'Dodati prečice na tastaturi', 1, 0),
    (44, 'Smanjiti veličinu JavaScript bundle-a', 1, 2),
    (44, 'Proveriti kontrast boja prema WCAG smernicama', 0, 0),
    (44, 'Podesiti logovanje i praćenje grešaka', 1, 2),
    (44, 'Podesiti red čekanja za obradu poruka', 0, 0),
    (44, 'Održati radionicu za krajnje korisnike', 1, 2),
    (44, 'Refaktorisati servisni sloj', 0, 2),
    (44, 'Implementirati registraciju korisnika', 1, 0),
    (44, 'Dodati deljenje stavki putem linka', 1, 2),
    (44, 'Ispraviti greške prijavljene u beta testiranju', 0, 1),
    (44, 'Napisati skriptu za početne podatke', 0, 1),
    (44, 'Dodati filtere po kategoriji i datumu', 2, 0),
    (44, 'Planirati drugu fazu razvoja', 2, 2),
    (44, 'Dodati keširanje čestih upita', 0, 1),
    (44, 'Napraviti stranicu sa uslovima korišćenja', 2, 2),
    (44, 'Pripremiti produkciono okruženje', 0, 1),
    (44, 'Implementirati komentare na stavkama', 2, 1),
    (44, 'Implementirati arhiviranje starih zapisa', 0, 1),
    (44, 'Dodati lenjo učitavanje slika', 0, 0),
    (44, 'Napraviti glavnu navigaciju i layout', 1, 1),
    (44, 'Ukloniti zastarele zavisnosti', 0, 0),
    (44, 'Napraviti widget za brzi pregled', 0, 1),
    (44, 'Implementirati dvofaktorsku prijavu', 0, 1),
    (45, 'Napisati REST endpoint za detalje stavke', 0, 2),
    (45, 'Integrisati sa spoljnim servisom za plaćanje', 1, 2),
    (45, 'Implementirati zakazane zadatke u pozadini', 1, 1),
    (45, 'Implementirati brisanje naloga sa potvrdom', 2, 1),
    (45, 'Nacrtati wireframe glavnih ekrana', 1, 2),
    (45, 'Implementirati višejezičnost', 0, 2),
    (45, 'Podesiti rezervne kopije baze', 1, 1),
    (45, 'Napraviti stranicu sa podešavanjima', 1, 1),
    (45, 'Dodati zaštitu od prekomernog broja zahteva', 1, 2),
    (45, 'Optimizovati vreme učitavanja početne stranice', 1, 2),
    (45, 'Implementirati komentare na stavkama', 2, 1),
    (45, 'Implementirati responzivan prikaz za mobilne uređaje', 0, 1),
    (45, 'Podesiti red čekanja za obradu poruka', 0, 0),
    (45, 'Refaktorisati servisni sloj', 1, 1),
    (45, 'Integrisati slanje e-pošte', 1, 1),
    (45, 'Postaviti Docker okruženje za razvoj', 1, 0),
    (45, 'Dodati kompresiju i promenu veličine slika', 0, 1),
    (45, 'Sprovesti testiranje opterećenja', 0, 1),
    (45, 'Dodati deljenje stavki putem linka', 1, 1),
    (45, 'Implementirati SSO prijavu preko Google naloga', 0, 1),
    (45, 'Implementirati favorite i liste želja', 2, 1),
    (45, 'Napraviti stranicu profila korisnika', 0, 1),
    (45, 'Dodati filtere po kategoriji i datumu', 0, 0),
    (45, 'Validirati forme na klijentskoj strani', 0, 0),
    (45, 'Dodati tamnu temu', 1, 1),
    (46, 'Implementirati pretragu po ključnoj reči', 2, 2),
    (46, 'Integrisati slanje e-pošte', 1, 1),
    (46, 'Implementirati QR kodove za brzi pristup', 0, 2),
    (46, 'Proveriti kontrast boja prema WCAG smernicama', 1, 1),
    (46, 'Dodati keširanje čestih upita', 1, 0),
    (46, 'Dodati kompresiju i promenu veličine slika', 0, 0),
    (46, 'Održati radionicu za krajnje korisnike', 1, 2),
    (46, 'Refaktorisati servisni sloj', 1, 0),
    (46, 'Optimizovati vreme učitavanja početne stranice', 0, 0),
    (46, 'Dodati prečice na tastaturi', 2, 2),
    (46, 'Dizajnirati šemu baze podataka', 2, 0),
    (46, 'Implementirati zakazane zadatke u pozadini', 2, 1),
    (46, 'Implementirati prijavu sa JWT tokenom', 1, 1),
    (46, 'Pregledati i zatvoriti stare tikete', 2, 1),
    (46, 'Implementirati otpremanje fajlova', 1, 1),
    (46, 'Implementirati arhiviranje starih zapisa', 0, 2),
    (46, 'Napisati end-to-end testove za glavne tokove', 0, 1),
    (46, 'Implementirati uloge i dozvole', 0, 1),
    (46, 'Napraviti kontrolnu tablu sa statistikom', 0, 0),
    (46, 'Dodati ocenjivanje i recenzije', 1, 2),
    (46, 'Dodati zaboravljenu lozinku sa slanjem e-pošte', 1, 2),
    (46, 'Dodati kolačić baner i politiku privatnosti', 2, 1),
    (46, 'Planirati drugu fazu razvoja', 1, 0),
    (46, 'Napraviti stranicu statusa sistema', 2, 0),
    (46, 'Dodati filtere po kategoriji i datumu', 1, 0),
    (47, 'Napraviti admin panel za upravljanje sadržajem', 0, 1),
    (47, 'Postaviti Docker okruženje za razvoj', 0, 1),
    (47, 'Dodati deljenje stavki putem linka', 1, 1),
    (47, 'Implementirati registraciju korisnika', 0, 2),
    (47, 'Napraviti stranicu sa uslovima korišćenja', 0, 0),
    (47, 'Implementirati SSO prijavu preko Google naloga', 0, 2),
    (47, 'Implementirati otpremanje fajlova', 1, 2),
    (47, 'Implementirati zakazane zadatke u pozadini', 1, 1),
    (47, 'Dodati paginaciju i sortiranje na listu', 1, 0),
    (47, 'Napraviti widget za brzi pregled', 1, 1),
    (47, 'Sprovesti testiranje opterećenja', 2, 2),
    (47, 'Implementirati favorite i liste želja', 0, 2),
    (47, 'Dodati lenjo učitavanje slika', 0, 1),
    (47, 'Implementirati izvoz podataka u CSV', 1, 1),
    (47, 'Dodati filtere po kategoriji i datumu', 1, 0),
    (47, 'Dodati kompresiju i promenu veličine slika', 0, 0),
    (47, 'Implementirati komentare na stavkama', 0, 0),
    (47, 'Podesiti HTTPS i sertifikate', 0, 0),
    (47, 'Definisati korisničke priče i kriterijume prihvatanja', 2, 2),
    (47, 'Implementirati izvoz izveštaja u PDF', 0, 2),
    (47, 'Dodati indekse na tabele sa najviše upita', 0, 1),
    (47, 'Integrisati push obaveštenja', 0, 1),
    (47, 'Dodati uvoz podataka iz Excel fajla', 0, 2),
    (47, 'Napisati migracije za početnu šemu', 2, 2),
    (47, 'Napraviti glavnu navigaciju i layout', 1, 2),
    (48, 'Podesiti red čekanja za obradu poruka', 0, 0),
    (48, 'Dodati tamnu temu', 0, 0),
    (48, 'Implementirati izvoz podataka u CSV', 0, 1),
    (48, 'Napraviti kontrolnu tablu sa statistikom', 0, 1),
    (48, 'Dodati kompresiju i promenu veličine slika', 2, 1),
    (48, 'Podesiti rezervne kopije baze', 0, 1),
    (48, 'Sprovesti testiranje opterećenja', 1, 1),
    (48, 'Sprovesti bezbednosni pregled zavisnosti', 2, 0),
    (48, 'Definisati korisničke priče i kriterijume prihvatanja', 1, 2),
    (48, 'Implementirati zakazane zadatke u pozadini', 1, 0),
    (48, 'Implementirati otpremanje fajlova', 0, 0),
    (48, 'Napisati dokumentaciju API-ja', 0, 0),
    (48, 'Implementirati favorite i liste želja', 1, 1),
    (48, 'Napisati skriptu za početne podatke', 0, 2),
    (48, 'Implementirati responzivan prikaz za mobilne uređaje', 0, 0),
    (48, 'Napraviti izveštaj o aktivnosti korisnika', 0, 1),
    (48, 'Optimizovati spore SQL upite', 0, 1),
    (48, 'Napisati REST endpoint za detalje stavke', 2, 1),
    (48, 'Integrisati push obaveštenja', 0, 1),
    (48, 'Implementirati QR kodove za brzi pristup', 0, 0),
    (48, 'Implementirati pretragu po ključnoj reči', 1, 2),
    (48, 'Implementirati meko brisanje zapisa', 0, 0),
    (48, 'Dodati paginaciju i sortiranje na listu', 0, 1),
    (48, 'Napraviti glavnu navigaciju i layout', 1, 2),
    (48, 'Dodati istoriju izmena za glavne entitete', 1, 1),
    (49, 'Napisati skriptu za početne podatke', 2, 1),
    (49, 'Pregledati i zatvoriti stare tikete', 2, 1),
    (49, 'Napraviti stranicu profila korisnika', 0, 1),
    (49, 'Dodati uvoz podataka iz Excel fajla', 1, 0),
    (49, 'Integrisati push obaveštenja', 0, 2),
    (49, 'Nacrtati wireframe glavnih ekrana', 2, 2),
    (49, 'Napisati uputstvo za korisnike', 2, 1),
    (49, 'Ispraviti greške prijavljene u beta testiranju', 0, 2),
    (49, 'Implementirati višejezičnost', 0, 1),
    (49, 'Optimizovati spore SQL upite', 0, 0),
    (49, 'Dodati prečice na tastaturi', 2, 0),
    (49, 'Dodati indekse na tabele sa najviše upita', 0, 2),
    (49, 'Poboljšati pristupačnost za čitače ekrana', 0, 1),
    (49, 'Implementirati registraciju korisnika', 0, 1),
    (49, 'Dodati istoriju izmena za glavne entitete', 1, 1),
    (49, 'Napraviti stranicu statusa sistema', 1, 1),
    (49, 'Podesiti nadzor dostupnosti servisa', 0, 1),
    (49, 'Napisati end-to-end testove za glavne tokove', 0, 0),
    (49, 'Napisati REST endpoint za listu stavki', 1, 1),
    (49, 'Dodati webhook obaveštenja za partnere', 0, 0),
    (49, 'Implementirati otpremanje fajlova', 1, 0),
    (49, 'Podesiti CI/CD pipeline', 0, 1),
    (49, 'Dodati kompresiju i promenu veličine slika', 2, 1),
    (49, 'Implementirati uloge i dozvole', 0, 0),
    (49, 'Nadograditi framework na najnoviju verziju', 2, 0),
    (50, 'Napisati REST endpoint za detalje stavke', 2, 1),
    (50, 'Implementirati izvoz izveštaja u PDF', 1, 0),
    (50, 'Dodati sinhronizaciju podataka između uređaja', 0, 0),
    (50, 'Dodati paginaciju i sortiranje na listu', 2, 2),
    (50, 'Napisati skriptu za početne podatke', 2, 2),
    (50, 'Pregledati i zatvoriti stare tikete', 0, 1),
    (50, 'Validirati unos na serverskoj strani', 0, 1),
    (50, 'Dodati keširanje čestih upita', 1, 2),
    (50, 'Implementirati responzivan prikaz za mobilne uređaje', 1, 2),
    (50, 'Podesiti HTTPS i sertifikate', 0, 1),
    (50, 'Implementirati prijavu sa JWT tokenom', 0, 0),
    (50, 'Napraviti stranicu profila korisnika', 2, 0),
    (50, 'Integrisati sa spoljnim servisom za plaćanje', 1, 0),
    (50, 'Podesiti nadzor dostupnosti servisa', 1, 1),
    (50, 'Napraviti izveštaj o aktivnosti korisnika', 0, 2),
    (50, 'Implementirati QR kodove za brzi pristup', 1, 1),
    (50, 'Dodati prečice na tastaturi', 1, 1),
    (50, 'Optimizovati spore SQL upite', 2, 2),
    (50, 'Dodati grafikone na kontrolnu tablu', 0, 0),
    (50, 'Proveriti kontrast boja prema WCAG smernicama', 2, 0),
    (50, 'Održati radionicu za krajnje korisnike', 2, 1),
    (50, 'Poboljšati pristupačnost za čitače ekrana', 1, 1),
    (50, 'Podesiti red čekanja za obradu poruka', 0, 0),
    (50, 'Implementirati favorite i liste želja', 2, 1),
    (50, 'Ukloniti zastarele zavisnosti', 0, 2);
